spring:
  jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_schema?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: admin